# Pre-commit hooks configuration
# See https://pre-commit.com for more information

default_language_version:
  python: python3

repos:
  # General file sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: requirements-txt-fixer
        files: requirements.*\.txt$

  # Ruff — fast Python linter + import sorter + partial security scan
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  # Pyupgrade — auto-modernize syntax for Python 3.8+
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # Pydocstyle — enforce docstring conventions (Google style)
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
          - --add-ignore=D100,D101,D102,D103,D104,D105,D107
        exclude: ^(tests/|setup\.py|docs/)

  # MyPy — static type checking (strict mode)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-setuptools
        args:
          [
            --ignore-missing-imports,
            --check-untyped-defs,
            --disallow-incomplete-defs,
            --warn-unused-ignores,
            --warn-redundant-casts,
            --no-implicit-optional,
          ]
        exclude: ^(tests/|setup\.py|docs/)

  # Prettier — format Markdown, YAML, JSON
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: ^(CHANGELOG\.md|LICENSE)$

  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint-fix
        args: [--disable, MD013, MD033, MD041, --]

  # YAML lint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args:
          [
            -d,
            "{extends: default, rules: {line-length: {max: 100}, document-start: disable}}",
          ]

  # Shell script lint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  # Optional: detect secrets / large commits
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
